Create DA for Access Groups
terraform-ibm-modules/terraform-ibm-iam-access-group pull request #233
Opened 2024-12-07 02:51 UTC by MatthewLemmond

### Description
Create a deployable architecture for the access group creation, utilizes the previously created module to define the accesses provided to the groups and allows for customization around things like names of the groups and adding users/service IDs to the groups

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Add deployable architecture to manage access groups

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-07 02:52 UTC, MatthewLemmond commented
/run pipeline

2024-12-09 13:36 UTC, MatthewLemmond commented
/run pipeline

2024-12-10 00:16 UTC, MatthewLemmond commented
/run pipeline

2024-12-10 15:26 UTC, MatthewLemmond commented
/run pipeline

2024-12-10 16:26 UTC, jor2 approved these changes
looks good

2024-12-10 16:26 UTC, jor2 commented on cra-config.yaml
> +      TF_VAR_prefix: "test"
maybe something more accurate like `access-management` or something?

2024-12-10 16:29 UTC, jor2 commented on ibm_catalog.json
> +              "key": "provider_visibility"
I've seen some other DA's use this format, maybe we should stay consistent?
````
            {
              "key": "provider_visibility",
              "options": [
                {
                  "displayname": "private",
                  "value": "private"
                },
                {
                  "displayname": "public",
                  "value": "public"
                },
                {
                  "displayname": "public-and-private",
                  "value": "public-and-private"
                }
              ]
            },
````

2024-12-10 22:47 UTC, MatthewLemmond commented
/run pipeline

2024-12-11 10:02 UTC, jor2 approved these changes

2024-12-11 16:45 UTC, ocofaigh requested changes
Left some comments. 
Also I need to create a new tile for this, and then you will need to add the `.catalog-onboard-pipeline.yaml` file and update the .releaserc file to onboard to the catalog pipeline. I will do that after your next commit (as I need the offering name updated in the catalog manifest first)

2024-12-12 16:25 UTC, MatthewLemmond commented
/run pipeline

2024-12-12 16:33 UTC, ocofaigh commented on ibm_catalog.json
> +            "controls": [],
remove this line

2024-12-12 16:40 UTC, MatthewLemmond commented
/run pipeline

2024-12-12 16:47 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 16:24 UTC, ocofaigh approved these changes
Lets go with this for now - Suggest to show at next deep dive for feedback

2024-12-13 16:24 UTC, merged

2024-12-13 16:25 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-iam-access-group/releases/tag/v1.4.0)
- `v1.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: